//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejar.Customer.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ejar.Customer.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejar.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in successfully.
        /// </summary>
        internal static string auth_login_success {
            get {
                return ResourceManager.GetString("auth.login.success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string auth_login_title {
            get {
                return ResourceManager.GetString("auth.login.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        internal static string auth_otp {
            get {
                return ResourceManager.GetString("auth.otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo code: 123456.
        /// </summary>
        internal static string auth_otp_demo {
            get {
                return ResourceManager.GetString("auth.otp.demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the 6-digit verification code.
        /// </summary>
        internal static string auth_otp_hint {
            get {
                return ResourceManager.GetString("auth.otp.hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string auth_phone {
            get {
                return ResourceManager.GetString("auth.phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number to continue.
        /// </summary>
        internal static string auth_phone_hint {
            get {
                return ResourceManager.GetString("auth.phone.hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code.
        /// </summary>
        internal static string auth_send_otp {
            get {
                return ResourceManager.GetString("auth.send_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed out.
        /// </summary>
        internal static string auth_signed_out {
            get {
                return ResourceManager.GetString("auth.signed_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string auth_verify {
            get {
                return ResourceManager.GetString("auth.verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About listing.
        /// </summary>
        internal static string chat_about_listing {
            get {
                return ResourceManager.GetString("chat.about_listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a message….
        /// </summary>
        internal static string chat_new_message {
            get {
                return ResourceManager.GetString("chat.new_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string chat_send {
            get {
                return ResourceManager.GetString("chat.send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start chat.
        /// </summary>
        internal static string chat_start {
            get {
                return ResourceManager.GetString("chat.start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string chat_title {
            get {
                return ResourceManager.GetString("chat.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string common_all {
            get {
                return ResourceManager.GetString("common.all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string common_apply {
            get {
                return ResourceManager.GetString("common.apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string common_cancel {
            get {
                return ResourceManager.GetString("common.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string common_close {
            get {
                return ResourceManager.GetString("common.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string common_confirm {
            get {
                return ResourceManager.GetString("common.confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        internal static string common_empty {
            get {
                return ResourceManager.GetString("common.empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string common_filter {
            get {
                return ResourceManager.GetString("common.filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        internal static string common_loading {
            get {
                return ResourceManager.GetString("common.loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string common_next {
            get {
                return ResourceManager.GetString("common.next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string common_prev {
            get {
                return ResourceManager.GetString("common.prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string common_reset {
            get {
                return ResourceManager.GetString("common.reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string common_retry {
            get {
                return ResourceManager.GetString("common.retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR.
        /// </summary>
        internal static string common_sar {
            get {
                return ResourceManager.GetString("common.sar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string common_save {
            get {
                return ResourceManager.GetString("common.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string common_search {
            get {
                return ResourceManager.GetString("common.search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string common_submit {
            get {
                return ResourceManager.GetString("common.submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string complaint_body {
            get {
                return ResourceManager.GetString("complaint.body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New complaint.
        /// </summary>
        internal static string complaint_new {
            get {
                return ResourceManager.GetString("complaint.new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string complaint_reply {
            get {
                return ResourceManager.GetString("complaint.reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string complaint_send {
            get {
                return ResourceManager.GetString("complaint.send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string complaint_status_closed {
            get {
                return ResourceManager.GetString("complaint.status.closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string complaint_status_open {
            get {
                return ResourceManager.GetString("complaint.status.open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        internal static string complaint_status_resolved {
            get {
                return ResourceManager.GetString("complaint.status.resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string complaint_subject {
            get {
                return ResourceManager.GetString("complaint.subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints.
        /// </summary>
        internal static string complaint_title {
            get {
                return ResourceManager.GetString("complaint.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorites yet.
        /// </summary>
        internal static string favorites_empty {
            get {
                return ResourceManager.GetString("favorites.empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string favorites_title {
            get {
                return ResourceManager.GetString("favorites.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string filter_city {
            get {
                return ResourceManager.GetString("filter.city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string filter_district {
            get {
                return ResourceManager.GetString("filter.district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max price.
        /// </summary>
        internal static string filter_price_max {
            get {
                return ResourceManager.GetString("filter.price_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min price.
        /// </summary>
        internal static string filter_price_min {
            get {
                return ResourceManager.GetString("filter.price_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string filter_sort {
            get {
                return ResourceManager.GetString("filter.sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: low to high.
        /// </summary>
        internal static string filter_sort_price_asc {
            get {
                return ResourceManager.GetString("filter.sort.price_asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: high to low.
        /// </summary>
        internal static string filter_sort_price_desc {
            get {
                return ResourceManager.GetString("filter.sort.price_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most viewed.
        /// </summary>
        internal static string filter_sort_views {
            get {
                return ResourceManager.GetString("filter.sort.views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental period.
        /// </summary>
        internal static string filter_time_unit {
            get {
                return ResourceManager.GetString("filter.time_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type.
        /// </summary>
        internal static string filter_type {
            get {
                return ResourceManager.GetString("filter.type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string help_contact {
            get {
                return ResourceManager.GetString("help.contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string help_faq {
            get {
                return ResourceManager.GetString("help.faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Support.
        /// </summary>
        internal static string help_title {
            get {
                return ResourceManager.GetString("help.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string home_categories_title {
            get {
                return ResourceManager.GetString("home.categories.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string home_city {
            get {
                return ResourceManager.GetString("home.city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your listing and start earning.
        /// </summary>
        internal static string home_cta_subtitle {
            get {
                return ResourceManager.GetString("home.cta.subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a property to rent?.
        /// </summary>
        internal static string home_cta_title {
            get {
                return ResourceManager.GetString("home.cta.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured listings.
        /// </summary>
        internal static string home_featured_title {
            get {
                return ResourceManager.GetString("home.featured.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newly added.
        /// </summary>
        internal static string home_new_title {
            get {
                return ResourceManager.GetString("home.new.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search apartments, villas, shops….
        /// </summary>
        internal static string home_search_placeholder {
            get {
                return ResourceManager.GetString("home.search.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemen&apos;s #1 rental app.
        /// </summary>
        internal static string home_subtitle {
            get {
                return ResourceManager.GetString("home.subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your perfect property.
        /// </summary>
        internal static string home_title {
            get {
                return ResourceManager.GetString("home.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        internal static string home_view_all {
            get {
                return ResourceManager.GetString("home.view_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string legal_privacy {
            get {
                return ResourceManager.GetString("legal.privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund policy.
        /// </summary>
        internal static string legal_refund {
            get {
                return ResourceManager.GetString("legal.refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return policy.
        /// </summary>
        internal static string legal_return {
            get {
                return ResourceManager.GetString("legal.return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of service.
        /// </summary>
        internal static string legal_terms {
            get {
                return ResourceManager.GetString("legal.terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amenities.
        /// </summary>
        internal static string listing_amenities {
            get {
                return ResourceManager.GetString("listing.amenities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string listing_area {
            get {
                return ResourceManager.GetString("listing.area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedrooms.
        /// </summary>
        internal static string listing_bedrooms {
            get {
                return ResourceManager.GetString("listing.bedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact landlord.
        /// </summary>
        internal static string listing_contact {
            get {
                return ResourceManager.GetString("listing.contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area (sqm).
        /// </summary>
        internal static string listing_create_field_area {
            get {
                return ResourceManager.GetString("listing.create.field.area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathrooms.
        /// </summary>
        internal static string listing_create_field_bathrooms {
            get {
                return ResourceManager.GetString("listing.create.field.bathrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedrooms.
        /// </summary>
        internal static string listing_create_field_bedrooms {
            get {
                return ResourceManager.GetString("listing.create.field.bedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type.
        /// </summary>
        internal static string listing_create_field_category {
            get {
                return ResourceManager.GetString("listing.create.field.category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string listing_create_field_city {
            get {
                return ResourceManager.GetString("listing.create.field.city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string listing_create_field_description {
            get {
                return ResourceManager.GetString("listing.create.field.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string listing_create_field_district {
            get {
                return ResourceManager.GetString("listing.create.field.district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string listing_create_field_price {
            get {
                return ResourceManager.GetString("listing.create.field.price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental period.
        /// </summary>
        internal static string listing_create_field_timeUnit {
            get {
                return ResourceManager.GetString("listing.create.field.timeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string listing_create_field_title {
            get {
                return ResourceManager.GetString("listing.create.field.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add listing.
        /// </summary>
        internal static string listing_create_title {
            get {
                return ResourceManager.GetString("listing.create.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily.
        /// </summary>
        internal static string listing_daily {
            get {
                return ResourceManager.GetString("listing.daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string listing_description {
            get {
                return ResourceManager.GetString("listing.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorites.
        /// </summary>
        internal static string listing_favorite_add {
            get {
                return ResourceManager.GetString("listing.favorite.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorites.
        /// </summary>
        internal static string listing_favorite_remove {
            get {
                return ResourceManager.GetString("listing.favorite.remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hourly.
        /// </summary>
        internal static string listing_hourly {
            get {
                return ResourceManager.GetString("listing.hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monthly.
        /// </summary>
        internal static string listing_monthly {
            get {
                return ResourceManager.GetString("listing.monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No listings found.
        /// </summary>
        internal static string listing_no_results {
            get {
                return ResourceManager.GetString("listing.no_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord.
        /// </summary>
        internal static string listing_owner {
            get {
                return ResourceManager.GetString("listing.owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string listing_price {
            get {
                return ResourceManager.GetString("listing.price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string listing_share {
            get {
                return ResourceManager.GetString("listing.share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        internal static string listing_verified {
            get {
                return ResourceManager.GetString("listing.verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to views.
        /// </summary>
        internal static string listing_views {
            get {
                return ResourceManager.GetString("listing.views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yearly.
        /// </summary>
        internal static string listing_yearly {
            get {
                return ResourceManager.GetString("listing.yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string my_listings_active {
            get {
                return ResourceManager.GetString("my_listings.active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add listing.
        /// </summary>
        internal static string my_listings_add {
            get {
                return ResourceManager.GetString("my_listings.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string my_listings_delete {
            get {
                return ResourceManager.GetString("my_listings.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No listings yet.
        /// </summary>
        internal static string my_listings_empty {
            get {
                return ResourceManager.GetString("my_listings.empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string my_listings_paused {
            get {
                return ResourceManager.GetString("my_listings.paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Listings.
        /// </summary>
        internal static string my_listings_title {
            get {
                return ResourceManager.GetString("my_listings.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle status.
        /// </summary>
        internal static string my_listings_toggle {
            get {
                return ResourceManager.GetString("my_listings.toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings.
        /// </summary>
        internal static string nav_bookings {
            get {
                return ResourceManager.GetString("nav.bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string nav_chats {
            get {
                return ResourceManager.GetString("nav.chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string nav_favorites {
            get {
                return ResourceManager.GetString("nav.favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string nav_home {
            get {
                return ResourceManager.GetString("nav.home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string nav_notifications {
            get {
                return ResourceManager.GetString("nav.notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string nav_profile {
            get {
                return ResourceManager.GetString("nav.profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string nav_search {
            get {
                return ResourceManager.GetString("nav.search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications.
        /// </summary>
        internal static string notification_empty {
            get {
                return ResourceManager.GetString("notification.empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all as read.
        /// </summary>
        internal static string notification_mark_all_read {
            get {
                return ResourceManager.GetString("notification.mark_all_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as read.
        /// </summary>
        internal static string notification_mark_read {
            get {
                return ResourceManager.GetString("notification.mark_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string notification_title {
            get {
                return ResourceManager.GetString("notification.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current plan.
        /// </summary>
        internal static string plans_current {
            get {
                return ResourceManager.GetString("plans.current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string plans_free {
            get {
                return ResourceManager.GetString("plans.free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listing.
        /// </summary>
        internal static string plans_listings_limit {
            get {
                return ResourceManager.GetString("plans.listings_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe now.
        /// </summary>
        internal static string plans_subscribe {
            get {
                return ResourceManager.GetString("plans.subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans &amp; Pricing.
        /// </summary>
        internal static string plans_title {
            get {
                return ResourceManager.GetString("plans.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string profile_city {
            get {
                return ResourceManager.GetString("profile.city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        internal static string profile_edit {
            get {
                return ResourceManager.GetString("profile.edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string profile_email {
            get {
                return ResourceManager.GetString("profile.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string profile_name {
            get {
                return ResourceManager.GetString("profile.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string profile_phone {
            get {
                return ResourceManager.GetString("profile.phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string profile_save {
            get {
                return ResourceManager.GetString("profile.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        internal static string profile_verified {
            get {
                return ResourceManager.GetString("profile.verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string settings_language {
            get {
                return ResourceManager.GetString("settings.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string settings_sign_out {
            get {
                return ResourceManager.GetString("settings.sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string settings_theme {
            get {
                return ResourceManager.GetString("settings.theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string settings_theme_dark {
            get {
                return ResourceManager.GetString("settings.theme.dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string settings_theme_light {
            get {
                return ResourceManager.GetString("settings.theme.light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings_title {
            get {
                return ResourceManager.GetString("settings.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change plan.
        /// </summary>
        internal static string subscription_change {
            get {
                return ResourceManager.GetString("subscription.change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days remaining.
        /// </summary>
        internal static string subscription_days_remaining {
            get {
                return ResourceManager.GetString("subscription.days_remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        internal static string subscription_invoices {
            get {
                return ResourceManager.GetString("subscription.invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        internal static string subscription_renew {
            get {
                return ResourceManager.GetString("subscription.renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Subscription.
        /// </summary>
        internal static string subscription_title {
            get {
                return ResourceManager.GetString("subscription.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listings used.
        /// </summary>
        internal static string subscription_usage {
            get {
                return ResourceManager.GetString("subscription.usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version.
        /// </summary>
        internal static string version_current {
            get {
                return ResourceManager.GetString("version.current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download latest.
        /// </summary>
        internal static string version_download {
            get {
                return ResourceManager.GetString("version.download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version.
        /// </summary>
        internal static string version_latest {
            get {
                return ResourceManager.GetString("version.latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update required.
        /// </summary>
        internal static string version_required {
            get {
                return ResourceManager.GetString("version.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update the app to continue.
        /// </summary>
        internal static string version_required_body {
            get {
                return ResourceManager.GetString("version.required_body", resourceCulture);
            }
        }
    }
}
